// Auto-generated by scripts/gen_p1_data.py — DO NOT EDIT MANUALLY
const PART1_DATA: { image: string; options: string[]; answer: 'A' | 'B' | 'C' | 'D' }[] = [
  // Photo 1: Unsplash ID 1556761175-b413da4baf72
  {
    image: '1556761175-b413da4baf72',
    options: [
      'Three colleagues are collaborating around a wooden desk with laptops in a modern open-plan office.',
      'A delivery truck is being unloaded at a warehouse loading dock.',
      'A technician is repairing a copy machine in a corridor.',
      'A customer is returning a product at a service counter.',
    ],
    answer: 'A',
  },
  // Photo 2: Unsplash ID 1497366216548-37526070297c
  {
    image: '1497366216548-37526070297c',
    options: [
      'A woman is speaking on the phone at her reception desk.',
      'An empty modern office corridor with glass partitions, polished floors, and a wooden shelving unit.',
      'People are entering a building through revolving glass doors.',
      'A security guard is checking identification badges at a desk.',
    ],
    answer: 'B',
  },
  // Photo 3: Unsplash ID 1524758631624-e2822e304c36
  {
    image: '1524758631624-e2822e304c36',
    options: [
      'A technician is repairing a copy machine in a copy room.',
      'Office workers are having a discussion near a window.',
      'A modern office lounge area with minimalist armchairs, a sofa, and a large black floor lamp.',
      'A delivery truck is being unloaded at a warehouse.',
    ],
    answer: 'C',
  },
  // Photo 4: Unsplash ID 1591115765373-5207764f72e7
  {
    image: '1591115765373-5207764f72e7',
    options: [
      'A worker is adjusting a ceiling light fixture.',
      'An employee is filing documents in a cabinet.',
      'Two colleagues are shaking hands in a hallway.',
      'A person is giving a presentation to a seated audience in an industrial-style office.',
    ],
    answer: 'D',
  },
  // Photo 5: Unsplash ID 1450101499163-c8848c66ca85
  {
    image: '1450101499163-c8848c66ca85',
    options: [
      'A delivery truck is being unloaded at a warehouse.',
      'A person in a blue shirt is signing a document with a pen on a desk.',
      'A team is collaborating around a conference table.',
      'A security guard is checking identification badges at a desk.',
    ],
    answer: 'B',
  },
  // Photo 6: Unsplash ID 1556740738-b6a63e27c4df
  {
    image: '1556740738-b6a63e27c4df',
    options: [
      'A group of employees are seated around a large conference table during a meeting.',
      'A janitor is mopping the floor in an empty hallway.',
      'A forklift is moving pallets in a warehouse.',
      'A chef is preparing food in a commercial kitchen.',
    ],
    answer: 'A',
  },
  // Photo 7: Unsplash ID 1517502884422-41eaead166d4
  {
    image: '1517502884422-41eaead166d4',
    options: [
      'A receptionist is greeting a visitor at the front desk of an office building.',
      'A mechanic is changing a tire in an auto repair shop.',
      'Children are playing on a playground at recess.',
      'A farmer is harvesting crops in a field.',
    ],
    answer: 'B',
  },
  // Photo 8: Unsplash ID 1504384308090-c894fdcc538d
  {
    image: '1504384308090-c894fdcc538d',
    options: [
      'Two business professionals are shaking hands after closing a deal in a boardroom.',
      'A painter is applying wallpaper in a residential room.',
      'A pilot is doing pre-flight checks on an aircraft.',
      'A librarian is shelving books in the stacks.',
    ],
    answer: 'C',
  },
  // Photo 9: Unsplash ID 1497215728101-856f4ea421fa
  {
    image: '1497215728101-856f4ea421fa',
    options: [
      'A team leader is writing on a whiteboard during a strategy session.',
      'A dentist is examining a patient's teeth.',
      'A barista is making espresso at a coffee shop.',
      'A lifeguard is scanning the pool area from a tall chair.',
    ],
    answer: 'D',
  },
  // Photo 10: Unsplash ID 1553028826-f4804a6dba3b
  {
    image: '1553028826-f4804a6dba3b',
    options: [
      'Colleagues are gathered around a laptop discussing a project in a bright office.',
      'A construction worker is pouring concrete from a mixer truck.',
      'A nurse is checking a patient's blood pressure.',
      'A photographer is adjusting a studio lighting setup.',
    ],
    answer: 'A',
  },
  // Photo 11: Unsplash ID 1573164713714-d95e436ab8d6
  {
    image: '1573164713714-d95e436ab8d6',
    options: [
      'An employee is typing on a laptop at a clean, organized desk with a potted plant.',
      'A plumber is fixing pipes under a kitchen sink.',
      'An astronaut is floating in zero gravity inside a space station.',
      'A fisherman is casting a net from a small boat.',
    ],
    answer: 'A',
  },
  // Photo 12: Unsplash ID 1498050108023-c5249f4df085
  {
    image: '1498050108023-c5249f4df085',
    options: [
      'A messy desk covered with paperwork, sticky notes, and two computer monitors.',
      'A surgeon is performing an operation in an operating room.',
      'A postal worker is sorting letters in a distribution center.',
      'A gymnast is performing a floor routine on a mat.',
    ],
    answer: 'B',
  },
  // Photo 13: Unsplash ID 1554224155-6726b3ff858f
  {
    image: '1554224155-6726b3ff858f',
    options: [
      'A standing desk with dual monitors, a keyboard, and a small succulent plant in a bright office.',
      'A welder is working on a steel beam at a construction site.',
      'A bus driver is checking passengers' tickets.',
      'A florist is arranging flowers in a shop window.',
    ],
    answer: 'C',
  },
  // Photo 14: Unsplash ID 1522071820081-009f0129c71c
  {
    image: '1522071820081-009f0129c71c',
    options: [
      'A corner office with a large window overlooking a city skyline and a mahogany desk.',
      'A plumber is fixing pipes under a kitchen sink.',
      'An astronaut is floating in zero gravity inside a space station.',
      'A fisherman is casting a net from a small boat.',
    ],
    answer: 'D',
  },
  // Photo 15: Unsplash ID 1515187029135-18ee286d815b
  {
    image: '1515187029135-18ee286d815b',
    options: [
      'A home office setup with a monitor, keyboard, and ergonomic chair in front of a window.',
      'A dentist is examining a patient's teeth.',
      'A barista is making espresso at a coffee shop.',
      'A lifeguard is scanning the pool area from a tall chair.',
    ],
    answer: 'A',
  },
  // Photo 16: Unsplash ID 1486312338219-ce68d2c6f44d
  {
    image: '1486312338219-ce68d2c6f44d',
    options: [
      'An open-plan workspace with rows of identical desks and task chairs under fluorescent lights.',
      'A chef is sautéing vegetables in a stainless steel pan.',
      'A librarian is shelving books in the stacks.',
      'A gymnast is performing a floor routine on a mat.',
    ],
    answer: 'B',
  },
  // Photo 17: Unsplash ID 1527192491265-7e15c55b1ed2
  {
    image: '1527192491265-7e15c55b1ed2',
    options: [
      'A minimalist desk with a tablet, a coffee mug, and a notepad in a sunlit room.',
      'A construction worker is pouring concrete from a mixer truck.',
      'A nurse is checking a patient's blood pressure.',
      'A photographer is adjusting a studio lighting setup.',
    ],
    answer: 'C',
  },
  // Photo 18: Unsplash ID 1497366754035-f200968a6e72
  {
    image: '1497366754035-f200968a6e72',
    options: [
      'A collaborative workspace with bean bags, whiteboards, and colorful wall art.',
      'A plumber is fixing pipes under a kitchen sink.',
      'An astronaut is floating in zero gravity inside a space station.',
      'A fisherman is casting a net from a small boat.',
    ],
    answer: 'D',
  },
  // Photo 19: Unsplash ID 1497215842964-222b430dc094
  {
    image: '1497215842964-222b430dc094',
    options: [
      'A private office with a glass desk, two monitors, and a filing cabinet against the wall.',
      'A mechanic is changing a tire in an auto repair shop.',
      'Children are playing on a playground at recess.',
      'A farmer is harvesting crops in a field.',
    ],
    answer: 'A',
  },
  // Photo 20: Unsplash ID 1519389950473-47ba0277781c
  {
    image: '1519389950473-47ba0277781c',
    options: [
      'A woman is writing on a notepad while seated at a conference table.',
      'A janitor is mopping the floor in an empty hallway.',
      'A forklift is moving pallets in a warehouse.',
      'A chef is preparing food in a commercial kitchen.',
    ],
    answer: 'B',
  },
  // Photo 21: Unsplash ID 1521737604893-d14cc237f11d
  {
    image: '1521737604893-d14cc237f11d',
    options: [
      'A man is reviewing printed reports while holding a cup of coffee at his desk.',
      'A painter is applying wallpaper in a residential room.',
      'A pilot is doing pre-flight checks on an aircraft.',
      'A librarian is shelving books in the stacks.',
    ],
    answer: 'C',
  },
  // Photo 22: Unsplash ID 1542744173-8e7e53415bb0
  {
    image: '1542744173-8e7e53415bb0',
    options: [
      'Two colleagues are looking at a tablet together in a break room.',
      'A dentist is examining a patient's teeth.',
      'A barista is making espresso at a coffee shop.',
      'A lifeguard is scanning the pool area from a tall chair.',
    ],
    answer: 'D',
  },
  // Photo 23: Unsplash ID 1497366811353-6870744d04b2
  {
    image: '1497366811353-6870744d04b2',
    options: [
      'A team of engineers is gathered around a prototype on a lab bench.',
      'A plumber is fixing pipes under a kitchen sink.',
      'An astronaut is floating in zero gravity inside a space station.',
      'A fisherman is casting a net from a small boat.',
    ],
    answer: 'A',
  },
  // Photo 24: Unsplash ID 1556761223-4c4282c73f77
  {
    image: '1556761223-4c4282c73f77',
    options: [
      'An accountant is working on a spreadsheet at a desk cluttered with calculators.',
      'A welder is working on a steel beam at a construction site.',
      'A bus driver is checking passengers' tickets.',
      'A florist is arranging flowers in a shop window.',
    ],
    answer: 'B',
  },
  // Photo 25: Unsplash ID 1521791136064-7986c2920216
  {
    image: '1521791136064-7986c2920216',
    options: [
      'A marketing specialist is brainstorming ideas on a colorful sticky-note wall.',
      'A surgeon is performing an operation in an operating room.',
      'A postal worker is sorting letters in a distribution center.',
      'A gymnast is performing a floor routine on a mat.',
    ],
    answer: 'C',
  },
  // Photo 26: Unsplash ID 1553877522-43269d4ea984
  {
    image: '1553877522-43269d4ea984',
    options: [
      'A project manager is pointing at a Gantt chart on a large wall display.',
      'A chef is sautéing vegetables in a stainless steel pan.',
      'A librarian is shelving books in the stacks.',
      'A gymnast is performing a floor routine on a mat.',
    ],
    answer: 'D',
  },
  // Photo 27: Unsplash ID 1531973576160-7125cd663d86
  {
    image: '1531973576160-7125cd663d86',
    options: [
      'A software developer is coding on a dual-monitor setup with a mechanical keyboard.',
      'A construction worker is pouring concrete from a mixer truck.',
      'A nurse is checking a patient's blood pressure.',
      'A photographer is adjusting a studio lighting setup.',
    ],
    answer: 'A',
  },
  // Photo 28: Unsplash ID 1560472354-b33ff0c44a43
  {
    image: '1560472354-b33ff0c44a43',
    options: [
      'A human resources officer is interviewing a candidate across a small table.',
      'A plumber is fixing pipes under a kitchen sink.',
      'An astronaut is floating in zero gravity inside a space station.',
      'A fisherman is casting a net from a small boat.',
    ],
    answer: 'B',
  },
  // Photo 29: Unsplash ID 1517245386807-bb43f82c33c4
  {
    image: '1517245386807-bb43f82c33c4',
    options: [
      'A logistics coordinator is checking shipping schedules on a large monitor.',
      'A mechanic is changing a tire in an auto repair shop.',
      'Children are playing on a playground at recess.',
      'A farmer is harvesting crops in a field.',
    ],
    answer: 'C',
  },
  // Photo 30: Unsplash ID 1513364776144-60967b0f800f
  {
    image: '1513364776144-60967b0f800f',
    options: [
      'A bright cafeteria with long tables, pendant lights, and employees eating lunch.',
      'A janitor is mopping the floor in an empty hallway.',
      'A forklift is moving pallets in a warehouse.',
      'A chef is preparing food in a commercial kitchen.',
    ],
    answer: 'D',
  },
  // Photo 31: Unsplash ID 1551836022-deb4988cc6c0
  {
    image: '1551836022-deb4988cc6c0',
    options: [
      'An executive boardroom with a long table, leather chairs, and a city view through floor-to-ceiling windows.',
      'A painter is applying wallpaper in a residential room.',
      'A pilot is doing pre-flight checks on an aircraft.',
      'A librarian is shelving books in the stacks.',
    ],
    answer: 'A',
  },
  // Photo 32: Unsplash ID 1497215842964-222b430dc095
  {
    image: '1497215842964-222b430dc095',
    options: [
      'A small startup office with exposed brick walls, hanging plants, and standing desks.',
      'A dentist is examining a patient's teeth.',
      'A barista is making espresso at a coffee shop.',
      'A lifeguard is scanning the pool area from a tall chair.',
    ],
    answer: 'B',
  },
  // Photo 33: Unsplash ID 1562654501-a0fec09beca6
  {
    image: '1562654501-a0fec09beca6',
    options: [
      'A reception area with a curved wooden desk, company logo on the wall, and comfortable seating.',
      'A plumber is fixing pipes under a kitchen sink.',
      'An astronaut is floating in zero gravity inside a space station.',
      'A fisherman is casting a net from a small boat.',
    ],
    answer: 'C',
  },
  // Photo 34: Unsplash ID 1556745757-8d76bdb6984b
  {
    image: '1556745757-8d76bdb6984b',
    options: [
      'A modern open office with rows of sit-stand desks and monitors under track lighting.',
      'A welder is working on a steel beam at a construction site.',
      'A bus driver is checking passengers' tickets.',
      'A florist is arranging flowers in a shop window.',
    ],
    answer: 'D',
  },
  // Photo 35: Unsplash ID 1507003211169-0a1dd7228f2d
  {
    image: '1507003211169-0a1dd7228f2d',
    options: [
      'A quiet library workspace with individual cubicles, desk lamps, and books on shelves.',
      'A surgeon is performing an operation in an operating room.',
      'A postal worker is sorting letters in a distribution center.',
      'A gymnast is performing a floor routine on a mat.',
    ],
    answer: 'A',
  },
  // Photo 36: Unsplash ID 1523240795612-9a054b0db644
  {
    image: '1523240795612-9a054b0db644',
    options: [
      'A glass-walled meeting room with a round table and six empty chairs.',
      'A chef is sautéing vegetables in a stainless steel pan.',
      'A librarian is shelving books in the stacks.',
      'A gymnast is performing a floor routine on a mat.',
    ],
    answer: 'B',
  },
  // Photo 37: Unsplash ID 1516321318423-f06f85e504b3
  {
    image: '1516321318423-f06f85e504b3',
    options: [
      'A co-working space with colorful furniture, a coffee bar, and people working on laptops.',
      'A construction worker is pouring concrete from a mixer truck.',
      'A nurse is checking a patient's blood pressure.',
      'A photographer is adjusting a studio lighting setup.',
    ],
    answer: 'C',
  },
  // Photo 38: Unsplash ID 1554469384-e58fac16e23a
  {
    image: '1554469384-e58fac16e23a',
    options: [
      'An atrium lobby with a tall indoor tree, marble floors, and a security desk.',
      'A plumber is fixing pipes under a kitchen sink.',
      'An astronaut is floating in zero gravity inside a space station.',
      'A fisherman is casting a net from a small boat.',
    ],
    answer: 'D',
  },
  // Photo 39: Unsplash ID 1507679799987-c73779587ccf
  {
    image: '1507679799987-c73779587ccf',
    options: [
      'A break room with a ping-pong table, a fridge, and a coffee machine on the counter.',
      'A mechanic is changing a tire in an auto repair shop.',
      'Children are playing on a playground at recess.',
      'A farmer is harvesting crops in a field.',
    ],
    answer: 'A',
  },
  // Photo 40: Unsplash ID 1568992687947-868a62a9f521
  {
    image: '1568992687947-868a62a9f521',
    options: [
      'A server room with rows of blinking racks and blue LED lighting.',
      'A janitor is mopping the floor in an empty hallway.',
      'A forklift is moving pallets in a warehouse.',
      'A chef is preparing food in a commercial kitchen.',
    ],
    answer: 'B',
  },
  // Photo 41: Unsplash ID 1556740758-90de374c12ad
  {
    image: '1556740758-90de374c12ad',
    options: [
      'A large format printer producing architectural blueprints on a roll of paper.',
      'A painter is applying wallpaper in a residential room.',
      'A pilot is doing pre-flight checks on an aircraft.',
      'A librarian is shelving books in the stacks.',
    ],
    answer: 'C',
  },
  // Photo 42: Unsplash ID 1559136555-9303baea8ebd
  {
    image: '1559136555-9303baea8ebd',
    options: [
      'A video conference call displayed on a 65-inch screen with four participants visible.',
      'A dentist is examining a patient's teeth.',
      'A barista is making espresso at a coffee shop.',
      'A lifeguard is scanning the pool area from a tall chair.',
    ],
    answer: 'D',
  },
  // Photo 43: Unsplash ID 1522202176988-66273c2fd55f
  {
    image: '1522202176988-66273c2fd55f',
    options: [
      'A 3D printer creating a prototype model on a build plate in a design lab.',
      'A plumber is fixing pipes under a kitchen sink.',
      'An astronaut is floating in zero gravity inside a space station.',
      'A fisherman is casting a net from a small boat.',
    ],
    answer: 'A',
  },
  // Photo 44: Unsplash ID 1560179707-f14e90ef3623
  {
    image: '1560179707-f14e90ef3623',
    options: [
      'A whiteboard filled with flowcharts, diagrams, and colored markers in a meeting room.',
      'A welder is working on a steel beam at a construction site.',
      'A bus driver is checking passengers' tickets.',
      'A florist is arranging flowers in a shop window.',
    ],
    answer: 'B',
  },
  // Photo 45: Unsplash ID 1551288049-bebda4e38f71
  {
    image: '1551288049-bebda4e38f71',
    options: [
      'A desk with a laptop, external keyboard, mouse, and two large monitors displaying code.',
      'A surgeon is performing an operation in an operating room.',
      'A postal worker is sorting letters in a distribution center.',
      'A gymnast is performing a floor routine on a mat.',
    ],
    answer: 'C',
  },
  // Photo 46: Unsplash ID 1576091160550-2173dba999ef
  {
    image: '1576091160550-2173dba999ef',
    options: [
      'A projector screen showing quarterly sales bar charts during a presentation.',
      'A chef is sautéing vegetables in a stainless steel pan.',
      'A librarian is shelving books in the stacks.',
      'A gymnast is performing a floor routine on a mat.',
    ],
    answer: 'D',
  },
  // Photo 47: Unsplash ID 1454165804606-c3d57bc86b40
  {
    image: '1454165804606-c3d57bc86b40',
    options: [
      'A tablet on a stand displaying a digital checklist next to a clipboard on a counter.',
      'A construction worker is pouring concrete from a mixer truck.',
      'A nurse is checking a patient's blood pressure.',
      'A photographer is adjusting a studio lighting setup.',
    ],
    answer: 'A',
  },
  // Photo 48: Unsplash ID 1505664194779-8beaceb93744
  {
    image: '1505664194779-8beaceb93744',
    options: [
      'An automated robotic arm assembling components on a production line.',
      'A plumber is fixing pipes under a kitchen sink.',
      'An astronaut is floating in zero gravity inside a space station.',
      'A fisherman is casting a net from a small boat.',
    ],
    answer: 'B',
  },
  // Photo 49: Unsplash ID 1566576912321-d58ddd7a6088
  {
    image: '1566576912321-d58ddd7a6088',
    options: [
      'A digital kiosk touchscreen displaying a building directory in an office lobby.',
      'A mechanic is changing a tire in an auto repair shop.',
      'Children are playing on a playground at recess.',
      'A farmer is harvesting crops in a field.',
    ],
    answer: 'C',
  },
  // Photo 50: Unsplash ID 1543286386-713bdd548da4
  {
    image: '1543286386-713bdd548da4',
    options: [
      'A group of employees walking through a glass-door entrance carrying briefcases.',
      'A janitor is mopping the floor in an empty hallway.',
      'A forklift is moving pallets in a warehouse.',
      'A chef is preparing food in a commercial kitchen.',
    ],
    answer: 'D',
  },
  // Photo 51: Unsplash ID 1513635269975-59663e0ac1ad
  {
    image: '1513635269975-59663e0ac1ad',
    options: [
      'A woman in business attire stepping out of an elevator on an office floor.',
      'A painter is applying wallpaper in a residential room.',
      'A pilot is doing pre-flight checks on an aircraft.',
      'A librarian is shelving books in the stacks.',
    ],
    answer: 'A',
  },
  // Photo 52: Unsplash ID 1558618666-fcd25c85f82e
  {
    image: '1558618666-fcd25c85f82e',
    options: [
      'Two colleagues walking down a hallway while reviewing documents on a tablet.',
      'A dentist is examining a patient's teeth.',
      'A barista is making espresso at a coffee shop.',
      'A lifeguard is scanning the pool area from a tall chair.',
    ],
    answer: 'B',
  },
  // Photo 53: Unsplash ID 1524661135-423995f22d0b
  {
    image: '1524661135-423995f22d0b',
    options: [
      'A person carrying a stack of file folders through an office corridor.',
      'A plumber is fixing pipes under a kitchen sink.',
      'An astronaut is floating in zero gravity inside a space station.',
      'A fisherman is casting a net from a small boat.',
    ],
    answer: 'C',
  },
  // Photo 54: Unsplash ID 1504384764586-bb4cdc1707b0
  {
    image: '1504384764586-bb4cdc1707b0',
    options: [
      'A courier delivering packages to a mailroom where employees are sorting mail.',
      'A welder is working on a steel beam at a construction site.',
      'A bus driver is checking passengers' tickets.',
      'A florist is arranging flowers in a shop window.',
    ],
    answer: 'D',
  },
  // Photo 55: Unsplash ID 1497366216548-37526070297d
  {
    image: '1497366216548-37526070297d',
    options: [
      'An employee holding a door open for a colleague carrying a laptop bag.',
      'A surgeon is performing an operation in an operating room.',
      'A postal worker is sorting letters in a distribution center.',
      'A gymnast is performing a floor routine on a mat.',
    ],
    answer: 'A',
  },
  // Photo 56: Unsplash ID 1497215728101-856f4ea421fb
  {
    image: '1497215728101-856f4ea421fb',
    options: [
      'A manager walking briskly through an open office with a coffee cup in hand.',
      'A chef is sautéing vegetables in a stainless steel pan.',
      'A librarian is shelving books in the stacks.',
      'A gymnast is performing a floor routine on a mat.',
    ],
    answer: 'B',
  },
  // Photo 57: Unsplash ID 1527192491265-7e15c55b1ed3
  {
    image: '1527192491265-7e15c55b1ed3',
    options: [
      'Two interns following a senior employee on a tour of the facility.',
      'A construction worker is pouring concrete from a mixer truck.',
      'A nurse is checking a patient's blood pressure.',
      'A photographer is adjusting a studio lighting setup.',
    ],
    answer: 'C',
  },
  // Photo 58: Unsplash ID 1519389950473-47ba0277781d
  {
    image: '1519389950473-47ba0277781d',
    options: [
      'A receptionist walking toward the front desk carrying a stack of mail.',
      'A plumber is fixing pipes under a kitchen sink.',
      'An astronaut is floating in zero gravity inside a space station.',
      'A fisherman is casting a net from a small boat.',
    ],
    answer: 'D',
  },
  // Photo 59: Unsplash ID 1521791136064-7986c2920217
  {
    image: '1521791136064-7986c2920217',
    options: [
      'A group of professionals exiting a train station during morning rush hour.',
      'A mechanic is changing a tire in an auto repair shop.',
      'Children are playing on a playground at recess.',
      'A farmer is harvesting crops in a field.',
    ],
    answer: 'A',
  },
  // Photo 60: Unsplash ID 1542744173-8e7e53415bb1
  {
    image: '1542744173-8e7e53415bb1',
    options: [
      'Employees gathered around a kitchen island eating lunch from takeout containers.',
      'A janitor is mopping the floor in an empty hallway.',
      'A forklift is moving pallets in a warehouse.',
      'A chef is preparing food in a commercial kitchen.',
    ],
    answer: 'B',
  },
  // Photo 61: Unsplash ID 1497366811353-6870744d04b3
  {
    image: '1497366811353-6870744d04b3',
    options: [
      'A coffee station with an espresso machine, cups, and a tip jar in an office pantry.',
      'A painter is applying wallpaper in a residential room.',
      'A pilot is doing pre-flight checks on an aircraft.',
      'A librarian is shelving books in the stacks.',
    ],
    answer: 'C',
  },
  // Photo 62: Unsplash ID 1556761223-4c4282c73f78
  {
    image: '1556761223-4c4282c73f78',
    options: [
      'A vending machine with snacks and drinks in the corner of an office break room.',
      'A dentist is examining a patient's teeth.',
      'A barista is making espresso at a coffee shop.',
      'A lifeguard is scanning the pool area from a tall chair.',
    ],
    answer: 'D',
  },
  // Photo 63: Unsplash ID 1521791136064-7986c2920218
  {
    image: '1521791136064-7986c2920218',
    options: [
      'Two coworkers chatting while waiting for the microwave in a shared kitchen.',
      'A plumber is fixing pipes under a kitchen sink.',
      'An astronaut is floating in zero gravity inside a space station.',
      'A fisherman is casting a net from a small boat.',
    ],
    answer: 'A',
  },
  // Photo 64: Unsplash ID 1553877522-43269d4ea985
  {
    image: '1553877522-43269d4ea985',
    options: [
      'A catered lunch spread on a buffet table with salads, sandwiches, and drinks.',
      'A welder is working on a steel beam at a construction site.',
      'A bus driver is checking passengers' tickets.',
      'A florist is arranging flowers in a shop window.',
    ],
    answer: 'B',
  },
  // Photo 65: Unsplash ID 1531973576160-7125cd663d87
  {
    image: '1531973576160-7125cd663d87',
    options: [
      'A person pouring hot water from a kettle into a tea cup at an office kitchen counter.',
      'A surgeon is performing an operation in an operating room.',
      'A postal worker is sorting letters in a distribution center.',
      'A gymnast is performing a floor routine on a mat.',
    ],
    answer: 'C',
  },
  // Photo 66: Unsplash ID 1560472354-b33ff0c44a44
  {
    image: '1560472354-b33ff0c44a44',
    options: [
      'An office fridge covered with magnets, name labels, and sticky notes.',
      'A chef is sautéing vegetables in a stainless steel pan.',
      'A librarian is shelving books in the stacks.',
      'A gymnast is performing a floor routine on a mat.',
    ],
    answer: 'D',
  },
  // Photo 67: Unsplash ID 1517245386807-bb43f82c33c5
  {
    image: '1517245386807-bb43f82c33c5',
    options: [
      'A group of colleagues sitting at an outdoor patio table during a coffee break.',
      'A construction worker is pouring concrete from a mixer truck.',
      'A nurse is checking a patient's blood pressure.',
      'A photographer is adjusting a studio lighting setup.',
    ],
    answer: 'A',
  },
  // Photo 68: Unsplash ID 1513364776144-60967b0f8010
  {
    image: '1513364776144-60967b0f8010',
    options: [
      'A snack drawer opened in a desk showing granola bars, nuts, and dried fruit.',
      'A plumber is fixing pipes under a kitchen sink.',
      'An astronaut is floating in zero gravity inside a space station.',
      'A fisherman is casting a net from a small boat.',
    ],
    answer: 'B',
  },
  // Photo 69: Unsplash ID 1551836022-deb4988cc6c1
  {
    image: '1551836022-deb4988cc6c1',
    options: [
      'A person stirring a mug of coffee while reading an email on their phone at a table.',
      'A mechanic is changing a tire in an auto repair shop.',
      'Children are playing on a playground at recess.',
      'A farmer is harvesting crops in a field.',
    ],
    answer: 'C',
  },
  // Photo 70: Unsplash ID 1497215842964-222b430dc096
  {
    image: '1497215842964-222b430dc096',
    options: [
      'A close-up of a hand writing notes in a lined notebook next to a laptop.',
      'A janitor is mopping the floor in an empty hallway.',
      'A forklift is moving pallets in a warehouse.',
      'A chef is preparing food in a commercial kitchen.',
    ],
    answer: 'D',
  },
  // Photo 71: Unsplash ID 1562654501-a0fec09beca7
  {
    image: '1562654501-a0fec09beca7',
    options: [
      'A person highlighting text in a printed contract with a yellow marker at a desk.',
      'A painter is applying wallpaper in a residential room.',
      'A pilot is doing pre-flight checks on an aircraft.',
      'A librarian is shelving books in the stacks.',
    ],
    answer: 'A',
  },
  // Photo 72: Unsplash ID 1556745757-8d76bdb6984c
  {
    image: '1556745757-8d76bdb6984c',
    options: [
      'An employee organizing documents into labeled folders in a filing cabinet.',
      'A dentist is examining a patient's teeth.',
      'A barista is making espresso at a coffee shop.',
      'A lifeguard is scanning the pool area from a tall chair.',
    ],
    answer: 'B',
  },
  // Photo 73: Unsplash ID 1507003211169-0a1dd7228f2e
  {
    image: '1507003211169-0a1dd7228f2e',
    options: [
      'A stack of printed reports with a red pen resting on top on a conference table.',
      'A plumber is fixing pipes under a kitchen sink.',
      'An astronaut is floating in zero gravity inside a space station.',
      'A fisherman is casting a net from a small boat.',
    ],
    answer: 'C',
  },
  // Photo 74: Unsplash ID 1523240795612-9a054b0db645
  {
    image: '1523240795612-9a054b0db645',
    options: [
      'A person stamping a document with an official company seal at a counter.',
      'A welder is working on a steel beam at a construction site.',
      'A bus driver is checking passengers' tickets.',
      'A florist is arranging flowers in a shop window.',
    ],
    answer: 'D',
  },
  // Photo 75: Unsplash ID 1516321318423-f06f85e504b4
  {
    image: '1516321318423-f06f85e504b4',
    options: [
      'A businesswoman reviewing a printed spreadsheet and making corrections with a pen.',
      'A surgeon is performing an operation in an operating room.',
      'A postal worker is sorting letters in a distribution center.',
      'A gymnast is performing a floor routine on a mat.',
    ],
    answer: 'A',
  },
  // Photo 76: Unsplash ID 1554469384-e58fac16e23b
  {
    image: '1554469384-e58fac16e23b',
    options: [
      'A person signing a contract at a desk with a fountain pen and a paperweight.',
      'A chef is sautéing vegetables in a stainless steel pan.',
      'A librarian is shelving books in the stacks.',
      'A gymnast is performing a floor routine on a mat.',
    ],
    answer: 'B',
  },
  // Photo 77: Unsplash ID 1507679799987-c73779587cd0
  {
    image: '1507679799987-c73779587cd0',
    options: [
      'An open planner on a desk with handwritten appointments and colorful sticky tabs.',
      'A construction worker is pouring concrete from a mixer truck.',
      'A nurse is checking a patient's blood pressure.',
      'A photographer is adjusting a studio lighting setup.',
    ],
    answer: 'C',
  },
  // Photo 78: Unsplash ID 1568992687947-868a62a9f522
  {
    image: '1568992687947-868a62a9f522',
    options: [
      'A pair of reading glasses resting on top of a stack of legal documents.',
      'A plumber is fixing pipes under a kitchen sink.',
      'An astronaut is floating in zero gravity inside a space station.',
      'A fisherman is casting a net from a small boat.',
    ],
    answer: 'D',
  },
  // Photo 79: Unsplash ID 1556740758-90de374c12ae
  {
    image: '1556740758-90de374c12ae',
    options: [
      'A close-up of a person typing on a laptop with a printed outline document beside them.',
      'A mechanic is changing a tire in an auto repair shop.',
      'Children are playing on a playground at recess.',
      'A farmer is harvesting crops in a field.',
    ],
    answer: 'A',
  },
  // Photo 80: Unsplash ID 1559136555-9303baea8ebe
  {
    image: '1559136555-9303baea8ebe',
    options: [
      'A receptionist sitting behind a curved desk answering a phone call.',
      'A janitor is mopping the floor in an empty hallway.',
      'A forklift is moving pallets in a warehouse.',
      'A chef is preparing food in a commercial kitchen.',
    ],
    answer: 'B',
  },
  // Photo 81: Unsplash ID 1522202176988-66273c2fd560
  {
    image: '1522202176988-66273c2fd560',
    options: [
      'A visitor signing in at a digital check-in kiosk in a modern office lobby.',
      'A painter is applying wallpaper in a residential room.',
      'A pilot is doing pre-flight checks on an aircraft.',
      'A librarian is shelving books in the stacks.',
    ],
    answer: 'C',
  },
  // Photo 82: Unsplash ID 1560179707-f14e90ef3624
  {
    image: '1560179707-f14e90ef3624',
    options: [
      'A waiting area with rows of chairs, a water cooler, and magazines on a coffee table.',
      'A dentist is examining a patient's teeth.',
      'A barista is making espresso at a coffee shop.',
      'A lifeguard is scanning the pool area from a tall chair.',
    ],
    answer: 'D',
  },
  // Photo 83: Unsplash ID 1551288049-bebda4e38f72
  {
    image: '1551288049-bebda4e38f72',
    options: [
      'A security guard monitoring CCTV screens at a front desk console.',
      'A plumber is fixing pipes under a kitchen sink.',
      'An astronaut is floating in zero gravity inside a space station.',
      'A fisherman is casting a net from a small boat.',
    ],
    answer: 'A',
  },
  // Photo 84: Unsplash ID 1576091160550-2173dba999f0
  {
    image: '1576091160550-2173dba999f0',
    options: [
      'A corporate lobby with a large company logo mounted on a stone feature wall.',
      'A welder is working on a steel beam at a construction site.',
      'A bus driver is checking passengers' tickets.',
      'A florist is arranging flowers in a shop window.',
    ],
    answer: 'B',
  },
  // Photo 85: Unsplash ID 1454165804606-c3d57bc86b41
  {
    image: '1454165804606-c3d57bc86b41',
    options: [
      'An elevator bank with brushed steel doors and floor indicators in an office tower.',
      'A surgeon is performing an operation in an operating room.',
      'A postal worker is sorting letters in a distribution center.',
      'A gymnast is performing a floor routine on a mat.',
    ],
    answer: 'C',
  },
  // Photo 86: Unsplash ID 1505664194779-8beaceb93745
  {
    image: '1505664194779-8beaceb93745',
    options: [
      'A visitor holding a lanyard badge while speaking with a receptionist.',
      'A chef is sautéing vegetables in a stainless steel pan.',
      'A librarian is shelving books in the stacks.',
      'A gymnast is performing a floor routine on a mat.',
    ],
    answer: 'D',
  },
  // Photo 87: Unsplash ID 1566576912321-d58ddd7a6089
  {
    image: '1566576912321-d58ddd7a6089',
    options: [
      'A person pressing the elevator button while carrying a briefcase in a lobby.',
      'A construction worker is pouring concrete from a mixer truck.',
      'A nurse is checking a patient's blood pressure.',
      'A photographer is adjusting a studio lighting setup.',
    ],
    answer: 'A',
  },
  // Photo 88: Unsplash ID 1543286386-713bdd548da5
  {
    image: '1543286386-713bdd548da5',
    options: [
      'An umbrella stand and coat rack near the entrance of an office building.',
      'A plumber is fixing pipes under a kitchen sink.',
      'An astronaut is floating in zero gravity inside a space station.',
      'A fisherman is casting a net from a small boat.',
    ],
    answer: 'B',
  },
  // Photo 89: Unsplash ID 1513635269975-59663e0ac1ae
  {
    image: '1513635269975-59663e0ac1ae',
    options: [
      'A directory board mounted on the wall listing company names and floor numbers.',
      'A mechanic is changing a tire in an auto repair shop.',
      'Children are playing on a playground at recess.',
      'A farmer is harvesting crops in a field.',
    ],
    answer: 'C',
  },
  // Photo 90: Unsplash ID 1558618666-fcd25c85f82f
  {
    image: '1558618666-fcd25c85f82f',
    options: [
      'A modern glass office building reflecting the sky with a landscaped entrance.',
      'A janitor is mopping the floor in an empty hallway.',
      'A forklift is moving pallets in a warehouse.',
      'A chef is preparing food in a commercial kitchen.',
    ],
    answer: 'D',
  },
  // Photo 91: Unsplash ID 1524661135-423995f22d0c
  {
    image: '1524661135-423995f22d0c',
    options: [
      'A corporate campus with a walking path, trees, and benches between two office buildings.',
      'A painter is applying wallpaper in a residential room.',
      'A pilot is doing pre-flight checks on an aircraft.',
      'A librarian is shelving books in the stacks.',
    ],
    answer: 'A',
  },
  // Photo 92: Unsplash ID 1504384764586-bb4cdc1707b1
  {
    image: '1504384764586-bb4cdc1707b1',
    options: [
      'A company parking lot with designated visitor spaces and directional signage.',
      'A dentist is examining a patient's teeth.',
      'A barista is making espresso at a coffee shop.',
      'A lifeguard is scanning the pool area from a tall chair.',
    ],
    answer: 'B',
  },
  // Photo 93: Unsplash ID 1497366216548-37526070297e
  {
    image: '1497366216548-37526070297e',
    options: [
      'A row of bicycles parked at a bike rack outside an office building.',
      'A plumber is fixing pipes under a kitchen sink.',
      'An astronaut is floating in zero gravity inside a space station.',
      'A fisherman is casting a net from a small boat.',
    ],
    answer: 'C',
  },
  // Photo 94: Unsplash ID 1497215728101-856f4ea421fc
  {
    image: '1497215728101-856f4ea421fc',
    options: [
      'A loading dock at the back of a commercial building with a delivery van parked.',
      'A welder is working on a steel beam at a construction site.',
      'A bus driver is checking passengers' tickets.',
      'A florist is arranging flowers in a shop window.',
    ],
    answer: 'D',
  },
  // Photo 95: Unsplash ID 1527192491265-7e15c55b1ed4
  {
    image: '1527192491265-7e15c55b1ed4',
    options: [
      'A plaza with outdoor seating, potted trees, and employees having a coffee break.',
      'A surgeon is performing an operation in an operating room.',
      'A postal worker is sorting letters in a distribution center.',
      'A gymnast is performing a floor routine on a mat.',
    ],
    answer: 'A',
  },
  // Photo 96: Unsplash ID 1519389950473-47ba0277781e
  {
    image: '1519389950473-47ba0277781e',
    options: [
      'A signpost with directional arrows pointing to different office wings on a campus.',
      'A chef is sautéing vegetables in a stainless steel pan.',
      'A librarian is shelving books in the stacks.',
      'A gymnast is performing a floor routine on a mat.',
    ],
    answer: 'B',
  },
  // Photo 97: Unsplash ID 1521791136064-7986c2920219
  {
    image: '1521791136064-7986c2920219',
    options: [
      'A flagpole with a company flag flying in front of a low-rise office building.',
      'A construction worker is pouring concrete from a mixer truck.',
      'A nurse is checking a patient's blood pressure.',
      'A photographer is adjusting a studio lighting setup.',
    ],
    answer: 'C',
  },
  // Photo 98: Unsplash ID 1542744173-8e7e53415bb2
  {
    image: '1542744173-8e7e53415bb2',
    options: [
      'An outdoor covered walkway connecting two buildings on a corporate campus.',
      'A plumber is fixing pipes under a kitchen sink.',
      'An astronaut is floating in zero gravity inside a space station.',
      'A fisherman is casting a net from a small boat.',
    ],
    answer: 'D',
  },
  // Photo 99: Unsplash ID 1497366811353-6870744d04b4
  {
    image: '1497366811353-6870744d04b4',
    options: [
      'A landscaped courtyard with a fountain, benches, and employees walking through.',
      'A mechanic is changing a tire in an auto repair shop.',
      'Children are playing on a playground at recess.',
      'A farmer is harvesting crops in a field.',
    ],
    answer: 'A',
  },
  // Photo 100: Unsplash ID 1556761223-4c4282c73f79
  {
    image: '1556761223-4c4282c73f79',
    options: [
      'A warehouse worker scanning a barcode on a cardboard box with a handheld scanner.',
      'A janitor is mopping the floor in an empty hallway.',
      'A forklift is moving pallets in a warehouse.',
      'A chef is preparing food in a commercial kitchen.',
    ],
    answer: 'B',
  },
  // Photo 101: Unsplash ID 1521791136064-7986c292021a
  {
    image: '1521791136064-7986c292021a',
    options: [
      'Stacked shipping boxes on a wooden pallet wrapped in clear plastic film.',
      'A painter is applying wallpaper in a residential room.',
      'A pilot is doing pre-flight checks on an aircraft.',
      'A librarian is shelving books in the stacks.',
    ],
    answer: 'C',
  },
  // Photo 102: Unsplash ID 1553877522-43269d4ea986
  {
    image: '1553877522-43269d4ea986',
    options: [
      'A conveyor belt moving packages toward a loading area in a distribution center.',
      'A dentist is examining a patient's teeth.',
      'A barista is making espresso at a coffee shop.',
      'A lifeguard is scanning the pool area from a tall chair.',
    ],
    answer: 'D',
  },
  // Photo 103: Unsplash ID 1531973576160-7125cd663d88
  {
    image: '1531973576160-7125cd663d88',
    options: [
      'A delivery driver loading boxes into the back of a white van at a loading bay.',
      'A plumber is fixing pipes under a kitchen sink.',
      'An astronaut is floating in zero gravity inside a space station.',
      'A fisherman is casting a net from a small boat.',
    ],
    answer: 'A',
  },
  // Photo 104: Unsplash ID 1560472354-b33ff0c44a45
  {
    image: '1560472354-b33ff0c44a45',
    options: [
      'A person taping shut a cardboard box on a packing table with a tape gun.',
      'A welder is working on a steel beam at a construction site.',
      'A bus driver is checking passengers' tickets.',
      'A florist is arranging flowers in a shop window.',
    ],
    answer: 'B',
  },
  // Photo 105: Unsplash ID 1517245386807-bb43f82c33c6
  {
    image: '1517245386807-bb43f82c33c6',
    options: [
      'A shipping label printer producing a label from a roll at a packing station.',
      'A surgeon is performing an operation in an operating room.',
      'A postal worker is sorting letters in a distribution center.',
      'A gymnast is performing a floor routine on a mat.',
    ],
    answer: 'C',
  },
  // Photo 106: Unsplash ID 1513364776144-60967b0f8011
  {
    image: '1513364776144-60967b0f8011',
    options: [
      'A receiving dock with stacked pallets and a worker checking a packing list.',
      'A chef is sautéing vegetables in a stainless steel pan.',
      'A librarian is shelving books in the stacks.',
      'A gymnast is performing a floor routine on a mat.',
    ],
    answer: 'D',
  },
  // Photo 107: Unsplash ID 1551836022-deb4988cc6c2
  {
    image: '1551836022-deb4988cc6c2',
    options: [
      'A worker weighing a sealed package on a digital scale before shipment.',
      'A construction worker is pouring concrete from a mixer truck.',
      'A nurse is checking a patient's blood pressure.',
      'A photographer is adjusting a studio lighting setup.',
    ],
    answer: 'A',
  },
  // Photo 108: Unsplash ID 1497215842964-222b430dc097
  {
    image: '1497215842964-222b430dc097',
    options: [
      'A mailroom with sorting bins labeled by department and a scale on the counter.',
      'A plumber is fixing pipes under a kitchen sink.',
      'An astronaut is floating in zero gravity inside a space station.',
      'A fisherman is casting a net from a small boat.',
    ],
    answer: 'B',
  },
  // Photo 109: Unsplash ID 1562654501-a0fec09beca8
  {
    image: '1562654501-a0fec09beca8',
    options: [
      'A hand placing a fragile sticker on a cardboard shipping box.',
      'A mechanic is changing a tire in an auto repair shop.',
      'Children are playing on a playground at recess.',
      'A farmer is harvesting crops in a field.',
    ],
    answer: 'C',
  },
  // Photo 110: Unsplash ID 1556745757-8d76bdb6984d
  {
    image: '1556745757-8d76bdb6984d',
    options: [
      'A presenter standing beside a projection screen showing a bar chart to an audience.',
      'A janitor is mopping the floor in an empty hallway.',
      'A forklift is moving pallets in a warehouse.',
      'A chef is preparing food in a commercial kitchen.',
    ],
    answer: 'D',
  },
  // Photo 111: Unsplash ID 1507003211169-0a1dd7228f2f
  {
    image: '1507003211169-0a1dd7228f2f',
    options: [
      'A trainer writing bullet points on a flip chart during a workshop session.',
      'A painter is applying wallpaper in a residential room.',
      'A pilot is doing pre-flight checks on an aircraft.',
      'A librarian is shelving books in the stacks.',
    ],
    answer: 'A',
  },
  // Photo 112: Unsplash ID 1523240795612-9a054b0db646
  {
    image: '1523240795612-9a054b0db646',
    options: [
      'An audience of employees seated in rows listening to a speaker at a podium.',
      'A dentist is examining a patient's teeth.',
      'A barista is making espresso at a coffee shop.',
      'A lifeguard is scanning the pool area from a tall chair.',
    ],
    answer: 'B',
  },
  // Photo 113: Unsplash ID 1516321318423-f06f85e504b5
  {
    image: '1516321318423-f06f85e504b5',
    options: [
      'A person pointing at a pie chart on a screen during a team meeting.',
      'A plumber is fixing pipes under a kitchen sink.',
      'An astronaut is floating in zero gravity inside a space station.',
      'A fisherman is casting a net from a small boat.',
    ],
    answer: 'C',
  },
  // Photo 114: Unsplash ID 1554469384-e58fac16e23c
  {
    image: '1554469384-e58fac16e23c',
    options: [
      'A classroom-style training room with desks, chairs, and a projector at the front.',
      'A welder is working on a steel beam at a construction site.',
      'A bus driver is checking passengers' tickets.',
      'A florist is arranging flowers in a shop window.',
    ],
    answer: 'D',
  },
  // Photo 115: Unsplash ID 1507679799987-c73779587cd1
  {
    image: '1507679799987-c73779587cd1',
    options: [
      'A new employee looking at a company handbook while sitting at a training desk.',
      'A surgeon is performing an operation in an operating room.',
      'A postal worker is sorting letters in a distribution center.',
      'A gymnast is performing a floor routine on a mat.',
    ],
    answer: 'A',
  },
  // Photo 116: Unsplash ID 1568992687947-868a62a9f523
  {
    image: '1568992687947-868a62a9f523',
    options: [
      'A speaker gesturing while explaining a diagram on a large presentation screen.',
      'A chef is sautéing vegetables in a stainless steel pan.',
      'A librarian is shelving books in the stacks.',
      'A gymnast is performing a floor routine on a mat.',
    ],
    answer: 'B',
  },
  // Photo 117: Unsplash ID 1556740758-90de374c12af
  {
    image: '1556740758-90de374c12af',
    options: [
      'Employees wearing headphones and watching a training video on individual monitors.',
      'A construction worker is pouring concrete from a mixer truck.',
      'A nurse is checking a patient's blood pressure.',
      'A photographer is adjusting a studio lighting setup.',
    ],
    answer: 'C',
  },
  // Photo 118: Unsplash ID 1559136555-9303baea8ebf
  {
    image: '1559136555-9303baea8ebf',
    options: [
      'A certificate of completion displayed on a desk next to a pen and folder.',
      'A plumber is fixing pipes under a kitchen sink.',
      'An astronaut is floating in zero gravity inside a space station.',
      'A fisherman is casting a net from a small boat.',
    ],
    answer: 'D',
  },
  // Photo 119: Unsplash ID 1522202176988-66273c2fd561
  {
    image: '1522202176988-66273c2fd561',
    options: [
      'A trainer handing out printed worksheets to participants at a conference table.',
      'A mechanic is changing a tire in an auto repair shop.',
      'Children are playing on a playground at recess.',
      'A farmer is harvesting crops in a field.',
    ],
    answer: 'A',
  },
  // Photo 120: Unsplash ID 1560179707-f14e90ef3625
  {
    image: '1560179707-f14e90ef3625',
    options: [
      'A person organizing binders on a supply shelf in an office storage room.',
      'A plumber is fixing pipes under a kitchen sink.',
      'An astronaut is floating in zero gravity inside a space station.',
      'A fisherman is casting a net from a small boat.',
    ],
    answer: 'B',
  },
];
